export const noDataPageConfig:any={
    listingPage:{
        path:"assets/MI-2.0-card-images/no-journeys-found.svg",
        messageTwo:"NO_DATA_MSG"
    },
    listingSearch:{
        path:"assets/MI-2.0-card-images/no-search-results.svg",
        messageTwo:"SEARCH_RESULT_NOT_FOUND"
    },
    myJourneyListing:{
        messageOne:"NO_PROBLEM_STATEMENT",
        path:"assets/MI-2.0-card-images/no-journeys-found.svg",
        messageTwo:"CREATE_OR_DISCOVER"
    },
    myJourneyOnGoing:{
        messageOne:"NO_ONGOING_PROJECTS",
        path:"assets/MI-2.0-card-images/no-journeys-found.svg",
    },
    myJourneyCompleted:{
        messageOne:"NO_COMPLETED_PROJECTS",
        path:"assets/MI-2.0-card-images/no-journeys-found.svg",
    }
}